#!/usr/bin/env bash
# Layer 1: make provision-core.ts support WebRTC endpoints (browser dialer).
# Run on the PBX from /opt/telroi-ai-app  (adjust path if needed).
set -e
cd /opt/telroi-ai-app
cp control-app/src/provision-core.ts control-app/src/provision-core.ts.bak

python3 - << 'PY'
p = 'control-app/src/provision-core.ts'
s = open(p).read()

# Edit 1: endpointConfig gains webrtc param + branches transport/media
old1 = """function endpointConfig(username: string, password: string, tenantId: string, label: string): string {
  return `; Auto-generated by Telroi provisioning - tenant ${tenantId}
; label: ${label}
[${username}]
type=endpoint
transport=${TRANSPORT}
context=${CONTEXT}
disallow=all
allow=opus
allow=ulaw
allow=alaw
auth=${username}-auth
aors=${username}
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[${username}-auth]"""
new1 = """function endpointConfig(username: string, password: string, tenantId: string, label: string, webrtc: boolean): string {
  const transport = webrtc ? 'transport-wss' : TRANSPORT;
  const mediaBlock = webrtc
    ? `webrtc=yes
dtls_auto_generate_cert=yes`
    : `direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes`;
  return `; Auto-generated by Telroi provisioning - tenant ${tenantId}
; label: ${label}${webrtc ? ' (webrtc)' : ''}
[${username}]
type=endpoint
transport=${transport}
context=${CONTEXT}
disallow=all
allow=opus
allow=ulaw
allow=alaw
auth=${username}-auth
aors=${username}
${mediaBlock}

[${username}-auth]"""
assert old1 in s, "endpointConfig block not found"
s = s.replace(old1, new1)

# Edit 2: provisionEndpoint accepts + passes webrtc, returns right transport
old2 = """export function provisionEndpoint(tenantId: string, label: string): ProvisionResult {
  const username = genUsername();
  const password = genPassword();
  const configPath = `${PJSIP_D}/${username}.conf`;

  ensurePlaceholder();
  writeFileSync(configPath, endpointConfig(username, password, tenantId, label), { mode: 0o640 });
  chownToAsterisk(configPath);
  pjsipReload();

  return { username, password, domain: SIP_DOMAIN, transport: TRANSPORT, context: CONTEXT, configPath };
}"""
new2 = """export function provisionEndpoint(tenantId: string, label: string, webrtc = false): ProvisionResult {
  const username = genUsername();
  const password = genPassword();
  const configPath = `${PJSIP_D}/${username}.conf`;

  ensurePlaceholder();
  writeFileSync(configPath, endpointConfig(username, password, tenantId, label, webrtc), { mode: 0o640 });
  chownToAsterisk(configPath);
  pjsipReload();

  const transport = webrtc ? 'transport-wss' : TRANSPORT;
  return { username, password, domain: SIP_DOMAIN, transport, context: CONTEXT, configPath };
}"""
assert old2 in s, "provisionEndpoint block not found"
s = s.replace(old2, new2)

open(p, 'w').write(s)
print("✓ provision-core.ts now supports webrtc endpoints")
PY

echo ""
echo "Now make the agent accept a webrtc flag in /provision (next step)."

# --- Also: make the agent pass a webrtc flag through to provisionEndpoint ---
python3 - << 'PY'
p = 'control-app/src/provision-agent.ts'
s = open(p).read()
old = """        const label = String(body.label || 'Provisioned device').slice(0, 120);
        if (!tenantId) return send(res, 400, { ok: false, error: 'tenantId required' });
        const result = provisionEndpoint(tenantId, label);"""
new = """        const label = String(body.label || 'Provisioned device').slice(0, 120);
        const webrtc = body.webrtc === true || body.webrtc === 'true';
        if (!tenantId) return send(res, 400, { ok: false, error: 'tenantId required' });
        const result = provisionEndpoint(tenantId, label, webrtc);"""
assert old in s, "provision route block not found"
s = s.replace(old, new)
open(p, 'w').write(s)
print("✓ provision-agent.ts passes webrtc flag")
PY

echo ""
echo "Layer 1 complete. Test by provisioning a webrtc endpoint:"
echo '  SECRET=$(grep PROVISION_AGENT_SECRET control-app/.env | cut -d= -f2-)'
echo '  curl -s -X POST http://127.0.0.1:8090/provision -H "Authorization: Bearer $SECRET" -H "Content-Type: application/json" -d '"'"'{"tenantId":"6f2e20be-1333-4e9a-9dcb-ffe41a24c9f1","label":"webrtc test","webrtc":true}'"'"
echo "Then: asterisk -rx \"pjsip show endpoint <returned-username>\" | grep -iE \"webrtc|transport\""
