// control-app/src/carrier-core.ts
// ───────────────────────────────────────────────────────────────────────────
// Carrier (SIP trunk) provisioning via CONFIG GENERATION. Mirrors the pattern
// in provision-core.ts but for OUTBOUND/INBOUND carrier trunks (Ruach, Kasooko,
// Sotel, and any new carrier added from the admin UI) rather than per-tenant
// endpoints.
//
// For each carrier <name> it writes TWO files and reloads Asterisk:
//   /etc/asterisk/pjsip.d/carrier-<name>.conf       (trunk: endpoint/aor/identify/auth)
//   /etc/asterisk/extensions.d/carrier-<name>.conf  (routes: outbound prefix + inbound context)
//
// Asterisk loads these via:
//   pjsip.conf      ->  #include "pjsip.d/*.conf"          (already present)
//   extensions.conf ->  #include "extensions.d/*.conf"     (ensured by ensureDialplanInclude)
// and the [internal] context pulls each carrier's outbound route via
//   include => carrier-<name>-out                          (ensured by ensureInternalInclude)
//
// Runs ON the Asterisk box (writes local config + reloads). DB writes are the
// caller's responsibility (the web app stores the encrypted carrier record).
// ───────────────────────────────────────────────────────────────────────────
import { writeFileSync, rmSync, existsSync, readFileSync, chownSync } from 'node:fs';
import { execFileSync, execSync } from 'node:child_process';

const PJSIP_D = process.env.PJSIP_D_DIR || '/etc/asterisk/pjsip.d';
const EXTENSIONS_D = process.env.EXTENSIONS_D_DIR || '/etc/asterisk/extensions.d';
const EXTENSIONS_CONF = process.env.EXTENSIONS_CONF || '/etc/asterisk/extensions.conf';
const INTERNAL_CONTEXT = process.env.PROVISION_CONTEXT || 'internal';

export interface CarrierInput {
  name: string;
  displayName?: string;
  prefix: string;
  sipGateway: string;
  sipPort?: number;
  transport?: string;
  sipDomain?: string;
  authUser?: string;
  authPass?: string;
  fromUser?: string;
  callerId?: string;
  codecs?: string[];
}

function assertName(name: string): void {
  if (!/^[a-z0-9]{2,32}$/.test(name)) {
    throw new Error(`Invalid carrier name "${name}" (must be lowercase a-z0-9, 2-32 chars)`);
  }
}
function assertPrefix(prefix: string): void {
  if (!/^[0-9]{2,4}$/.test(prefix)) {
    throw new Error(`Invalid prefix "${prefix}" (must be 2-4 digits)`);
  }
}

function chownToAsterisk(path: string): void {
  try {
    const uid = parseInt(execSync('id -u asterisk').toString().trim(), 10);
    const gid = parseInt(execSync('id -g asterisk').toString().trim(), 10);
    chownSync(path, uid, gid);
  } catch {
    try { execSync(`chmod 0644 ${path}`); } catch { /* best effort */ }
  }
}

function trunkConfig(c: CarrierInput): string {
  const port = c.sipPort || 5060;
  const transport = `transport-${(c.transport || 'udp').toLowerCase()}`;
  const domain = c.sipDomain || c.sipGateway;
  const codecs = (c.codecs && c.codecs.length ? c.codecs : ['ulaw', 'alaw'])
    .map((x) => `allow=${x}`).join('\n');
  const useAuth = !!(c.authUser && c.authPass);

  // The trunk is a PURE TRANSPORT — no from_user / callerid baked in. Caller ID
  // is set per-call in the dialplan from the secure ODBC per-customer lookup.
  let out = `; Auto-generated by Telroi carrier provisioning — ${c.displayName || c.name}
[${c.name}-endpoint]
type=endpoint
transport=${transport}
context=from-${c.name}
disallow=all
${codecs}
aors=${c.name}-aor
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
`;
  if (useAuth) out += `outbound_auth=${c.name}-auth\n`;

  out += `
[${c.name}-aor]
type=aor
contact=sip:${c.sipGateway}:${port}
qualify_frequency=60
qualify_timeout=3

[${c.name}-identify]
type=identify
endpoint=${c.name}-endpoint
match=${c.sipGateway}
`;
  if (domain && domain !== c.sipGateway) out += `match=${domain}\n`;

  if (useAuth) {
    out += `
[${c.name}-auth]
type=auth
auth_type=userpass
username=${c.authUser}
password=${c.authPass}
`;
  }
  return out;
}

function routeConfig(c: CarrierInput): string {
  const domain = c.sipDomain || c.sipGateway;
  const port = c.sipPort || 5060;
  const useAuthDomain = c.authUser ? domain : `${domain}:${port}`;
  const strip = c.prefix.length;
  // Caller ID comes ONLY from the secure per-customer ODBC lookup. If it resolves
  // empty (caller owns no DID on this carrier) the call is REJECTED — never sent
  // with a fallback number. The app blocks this upstream; this is defense in depth.
  return `; Auto-generated by Telroi carrier provisioning — ${c.displayName || c.name}
[carrier-${c.name}-out]
exten => _${c.prefix}234XXXXXXXXXX,1,NoOp(${c.displayName || c.name} ${c.prefix}: \${EXTEN:${strip}})
 same => n,Set(CID=\${ODBC_CALLERID_FOR(\${CHANNEL(endpoint)},${c.name})})
 same => n,GotoIf($["\${CID}"=""]?nodid)
 same => n,Set(CALLERID(num)=\${CID})
 same => n,Set(CALLERID(name)=Telroi)
 same => n,Set(TELROI_START=\${EPOCH})
 same => n,Dial(PJSIP/${c.name}-endpoint/sip:\${EXTEN:${strip}}@${useAuthDomain},60)
 same => n,Set(TELROI_LOG=\${CURL(http://127.0.0.1:8090/log-outbound?callid=\${UNIQUEID}&agent=\${CHANNEL(endpoint)}&dialed=\${EXTEN:${strip}}&carrier=${c.name}&dialstatus=\${DIALSTATUS}&hangupcause=\${HANGUPCAUSE}&duration=\${CDR(billsec)}&start=\${TELROI_START})})
 same => n,Hangup()
 same => n(nodid),NoOp(Rejected: caller owns no DID on ${c.name} — buy/select a DID or contact support)
 same => n,Hangup(21)

[from-${c.name}]
exten => _X.,1,NoOp(Inbound from ${c.displayName || c.name} -> DID \${EXTEN} from \${CALLERID(num)})
 same => n,Stasis(telroi,\${EXTEN})
 same => n,Hangup()
`;
}

const EXT_D_PLACEHOLDER = `${EXTENSIONS_D}/00-placeholder.conf`;

function ensureExtDirPlaceholder(): void {
  try {
    execSync(`mkdir -p ${EXTENSIONS_D}`);
    if (!existsSync(EXT_D_PLACEHOLDER)) {
      writeFileSync(EXT_D_PLACEHOLDER, '; placeholder so extensions.d/*.conf always matches at least one file\n', { mode: 0o640 });
      chownToAsterisk(EXT_D_PLACEHOLDER);
    }
  } catch { /* best effort */ }
}

function ensureDialplanInclude(): void {
  ensureExtDirPlaceholder();
  const conf = readFileSync(EXTENSIONS_CONF, 'utf8');
  if (conf.includes('extensions.d/*.conf')) return;
  const addition = `\n; Telroi: per-carrier generated dialplan (one file per carrier)\n#include "extensions.d/*.conf"\n`;
  writeFileSync(EXTENSIONS_CONF, conf + addition, { mode: 0o640 });
}

function ensureInternalInclude(name: string): void {
  const conf = readFileSync(EXTENSIONS_CONF, 'utf8');
  const incLine = `include => carrier-${name}-out`;
  if (conf.includes(incLine)) return;
  const marker = `[${INTERNAL_CONTEXT}]`;
  const idx = conf.indexOf(marker);
  if (idx === -1) throw new Error(`[${INTERNAL_CONTEXT}] context not found in ${EXTENSIONS_CONF}`);
  const lineEnd = conf.indexOf('\n', idx);
  const updated = conf.slice(0, lineEnd + 1) + incLine + '\n' + conf.slice(lineEnd + 1);
  writeFileSync(EXTENSIONS_CONF, updated, { mode: 0o640 });
}

function removeInternalInclude(name: string): void {
  const conf = readFileSync(EXTENSIONS_CONF, 'utf8');
  const incLine = `include => carrier-${name}-out\n`;
  if (!conf.includes(incLine)) return;
  writeFileSync(EXTENSIONS_CONF, conf.replace(incLine, ''), { mode: 0o640 });
}

function pjsipReload(): void {
  execFileSync('asterisk', ['-rx', 'pjsip reload'], { stdio: 'pipe' });
}
function dialplanReload(): void {
  execFileSync('asterisk', ['-rx', 'dialplan reload'], { stdio: 'pipe' });
}

export interface CarrierResult {
  name: string;
  prefix: string;
  pjsipPath: string;
  extensionsPath: string;
}

export function upsertCarrier(c: CarrierInput): CarrierResult {
  assertName(c.name);
  assertPrefix(c.prefix);
  if (!c.sipGateway) throw new Error('sipGateway is required');

  const pjsipPath = `${PJSIP_D}/carrier-${c.name}.conf`;
  const extensionsPath = `${EXTENSIONS_D}/carrier-${c.name}.conf`;

  ensureDialplanInclude();
  ensureExtDirPlaceholder();

  writeFileSync(pjsipPath, trunkConfig(c), { mode: 0o640 });
  chownToAsterisk(pjsipPath);
  writeFileSync(extensionsPath, routeConfig(c), { mode: 0o640 });
  chownToAsterisk(extensionsPath);

  ensureInternalInclude(c.name);

  pjsipReload();
  dialplanReload();

  return { name: c.name, prefix: c.prefix, pjsipPath, extensionsPath };
}

export function removeCarrier(name: string): { removed: boolean } {
  assertName(name);
  const pjsipPath = `${PJSIP_D}/carrier-${name}.conf`;
  const extensionsPath = `${EXTENSIONS_D}/carrier-${name}.conf`;
  const existed = existsSync(pjsipPath) || existsSync(extensionsPath);
  if (existsSync(pjsipPath)) rmSync(pjsipPath, { force: true });
  if (existsSync(extensionsPath)) rmSync(extensionsPath, { force: true });
  removeInternalInclude(name);
  ensureExtDirPlaceholder();
  pjsipReload();
  dialplanReload();
  return { removed: existed };
}
