// control-app/src/provision-core.ts
// ───────────────────────────────────────────────────────────────────────────
// Shared SIP-endpoint provisioning logic (config-generation, NOT realtime).
//
// Used by both:
//   • src/provision.ts        — the CLI validation harness
//   • src/provision-agent.ts  — the authenticated HTTP endpoint the web app calls
//
// This module ONLY touches Asterisk (writes the per-client config file into
// /etc/asterisk/pjsip.d/, chowns it to the asterisk user, runs `pjsip reload`).
// It deliberately does NOT write the sip_endpoints DB row — the caller owns that
// (the web app writes sip_endpoints with its own encrypt(); the CLI writes it for
// standalone testing). Keeping DB-writes out of here means the agent has a single
// responsibility: make Asterisk serve (or stop serving) an endpoint.
// ───────────────────────────────────────────────────────────────────────────
import crypto from 'node:crypto';
import { writeFileSync, rmSync, existsSync, chownSync } from 'node:fs';
import { execFileSync, execSync } from 'node:child_process';

export interface ProvisionResult {
  username: string;
  password: string;
  domain: string;
  transport: string;
  context: string;
  configPath: string;
}

const SIP_DOMAIN = process.env.SIP_DOMAIN || 'sip.telroi.ai';
const TRANSPORT = process.env.PROVISION_TRANSPORT || 'transport-udp';
const CONTEXT = process.env.PROVISION_CONTEXT || 'internal';
const PJSIP_D = process.env.PJSIP_D_DIR || '/etc/asterisk/pjsip.d';

export function genUsername(): string {
  return 'tnt_' + crypto.randomBytes(4).toString('hex');
}
export function genPassword(): string {
  return crypto.randomBytes(18).toString('base64').replace(/[^a-zA-Z0-9]/g, '').slice(0, 20);
}

function endpointConfig(username: string, password: string, tenantId: string, label: string): string {
  return `; Auto-generated by Telroi provisioning - tenant ${tenantId}
; label: ${label}
[${username}]
type=endpoint
transport=${TRANSPORT}
context=${CONTEXT}
disallow=all
allow=opus
allow=ulaw
allow=alaw
auth=${username}-auth
aors=${username}
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[${username}-auth]
type=auth
auth_type=userpass
username=${username}
password=${password}

[${username}]
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=30
`;
}

// Make the generated file readable by the 'asterisk' user (the script usually
// runs as root, producing root:root 0640 which Asterisk can't read).
function chownToAsterisk(path: string): void {
  try {
    const uid = parseInt(execSync('id -u asterisk').toString().trim(), 10);
    const gid = parseInt(execSync('id -g asterisk').toString().trim(), 10);
    chownSync(path, uid, gid);
  } catch {
    // Could not resolve the asterisk user — widen perms so Asterisk can read.
    try { execSync(`chmod 0644 ${path}`); } catch { /* best effort */ }
  }
}

// The pjsip.conf include `#include "pjsip.d/*.conf"` ERRORS if the glob matches
// zero files, which makes Asterisk fail to load the ENTIRE pjsip.conf (dropping
// all endpoints/transports). So we keep a harmless placeholder file in the dir
// at all times — provisioning ensures it exists, and deprovisioning never lets
// the directory go empty.
const PLACEHOLDER = `${PJSIP_D}/00-placeholder.conf`;
function ensurePlaceholder(): void {
  try {
    if (!existsSync(PLACEHOLDER)) {
      writeFileSync(PLACEHOLDER, '; placeholder so pjsip.d/*.conf always matches at least one file\n', { mode: 0o640 });
      chownToAsterisk(PLACEHOLDER);
    }
  } catch { /* best effort */ }
}

function pjsipReload(): void {
  execFileSync('asterisk', ['-rx', 'pjsip reload'], { stdio: 'pipe' });
}

/**
 * Provision a new SIP endpoint on Asterisk. Generates credentials, writes the
 * config file, makes it readable, reloads PJSIP. Returns the credentials so the
 * caller can store them (encrypted) and show them to the client once.
 */
export function provisionEndpoint(tenantId: string, label: string): ProvisionResult {
  const username = genUsername();
  const password = genPassword();
  const configPath = `${PJSIP_D}/${username}.conf`;

  ensurePlaceholder();
  writeFileSync(configPath, endpointConfig(username, password, tenantId, label), { mode: 0o640 });
  chownToAsterisk(configPath);
  pjsipReload();

  return { username, password, domain: SIP_DOMAIN, transport: TRANSPORT, context: CONTEXT, configPath };
}

/**
 * Remove a previously-provisioned endpoint: delete its config file and reload.
 * Idempotent — succeeds even if the file is already gone.
 */
export function deprovisionEndpoint(username: string): { removed: boolean } {
  // Guard the username so we only ever touch our generated files.
  if (!/^tnt_[a-f0-9]{8}$/.test(username)) {
    throw new Error(`Refusing to deprovision unexpected username: ${username}`);
  }
  const configPath = `${PJSIP_D}/${username}.conf`;
  const existed = existsSync(configPath);
  if (existed) rmSync(configPath, { force: true });
  ensurePlaceholder(); // never let the directory go empty (would break the include)
  pjsipReload();
  return { removed: existed };
}
