// control-app/src/provision.ts
// SIP endpoint provisioning via CONFIG GENERATION (not realtime).
//
// We deliberately do NOT use PJSIP Realtime (it destabilized the PBX). Instead,
// provisioning writes a per-client PJSIP config file into /etc/asterisk/pjsip.d/
// and runs `pjsip reload`. Asterisk loads it via #include "pjsip.d/*.conf" in
// pjsip.conf. This stays on the reliable static-config path.
//
// USAGE: node --experimental-strip-types src/provision.ts <tenantId> [label]
// Runs ON the Asterisk box (writes local config + reloads).
import 'dotenv/config';
import crypto from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import postgres from 'postgres';

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) { console.error('Missing DATABASE_URL'); process.exit(1); }

const tenantId = process.argv[2];
const label = process.argv[3] || 'Provisioned device';
if (!tenantId) {
  console.error('Usage: node --experimental-strip-types src/provision.ts <tenantId> [label]');
  process.exit(1);
}

const SIP_DOMAIN = process.env.SIP_DOMAIN || 'sip.telroi.ai';
const TRANSPORT = process.env.PROVISION_TRANSPORT || 'transport-udp';
const CONTEXT = process.env.PROVISION_CONTEXT || 'internal';
const PJSIP_D = process.env.PJSIP_D_DIR || '/etc/asterisk/pjsip.d';

function genUsername(): string {
  return 'tnt_' + crypto.randomBytes(4).toString('hex');
}
function genPassword(): string {
  return crypto.randomBytes(18).toString('base64').replace(/[^a-zA-Z0-9]/g, '').slice(0, 20);
}

function endpointConfig(username: string, password: string): string {
  return `; Auto-generated by Telroi provisioning - tenant ${tenantId}
; label: ${label}
[${username}]
type=endpoint
transport=${TRANSPORT}
context=${CONTEXT}
disallow=all
allow=opus
allow=ulaw
allow=alaw
auth=${username}-auth
aors=${username}
direct_media=no

[${username}-auth]
type=auth
auth_type=userpass
username=${username}
password=${password}

[${username}]
type=aor
max_contacts=1
remove_existing=yes
`;
}

const sql = postgres(DATABASE_URL, { max: 2 });

async function main() {
  const username = genUsername();
  const password = genPassword();

  const path = `${PJSIP_D}/${username}.conf`;
  try {
    writeFileSync(path, endpointConfig(username, password), { mode: 0o640 });
  } catch (err) {
    console.error(`Failed to write ${path}:`, (err as Error).message);
    console.error('Are you running on the Asterisk box with write access to', PJSIP_D, '?');
    await sql.end();
    process.exit(1);
  }

  try {
    execFileSync('asterisk', ['-rx', 'pjsip reload'], { stdio: 'pipe' });
  } catch (err) {
    console.error('pjsip reload failed:', (err as Error).message);
    console.error('Config written to', path, '- reload manually with: asterisk -rx "pjsip reload"');
  }

  const secretField = encryptSecret(password);
  const rows = await sql`
    INSERT INTO sip_endpoints (tenant_id, provider, kind, label, sip_username, secret_enc, domain)
    VALUES (${tenantId}, 'telroi', 'webrtc_user', ${label}, ${username}, ${secretField.value}, ${SIP_DOMAIN})
    RETURNING id
  `;
  const endpointId = rows[0].id;

  console.log('\nProvisioned SIP endpoint (config-generation)');
  console.log('-------------------------------------');
  console.log('  sip_endpoints.id :', endpointId, '  <-- put THIS in number_subscriptions.route_target (Option B)');
  console.log('  SIP username     :', username);
  console.log('  SIP password     :', password);
  console.log('  Domain / server  :', SIP_DOMAIN);
  console.log('  Port / transport : 5060 / UDP');
  console.log('  Config file      :', path);
  console.log('  Tenant           :', tenantId);
  if (!secretField.encrypted) {
    console.log('  WARNING: secret stored UNENCRYPTED (no ENCRYPTION_KEY set) - dev only.');
  }
  console.log('-------------------------------------');
  console.log('Register a softphone with the username/password above, then set a');
  console.log('number_subscriptions.route_target to the sip_endpoints.id and dial it.\n');

  await sql.end();
}

function encryptSecret(plain: string): { value: string; encrypted: boolean } {
  const keyRaw = process.env.ENCRYPTION_KEY;
  if (!keyRaw) return { value: plain, encrypted: false };
  try {
    const key = keyRaw.length === 64 ? Buffer.from(keyRaw, 'hex') : Buffer.from(keyRaw, 'base64');
    if (key.length !== 32) return { value: plain, encrypted: false };
    const iv = crypto.randomBytes(12);
    const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
    const enc = Buffer.concat([cipher.update(plain, 'utf8'), cipher.final()]);
    const tag = cipher.getAuthTag();
    const packed = [iv.toString('base64'), tag.toString('base64'), enc.toString('base64')].join(':');
    return { value: packed, encrypted: true };
  } catch {
    return { value: plain, encrypted: false };
  }
}

main().catch((err) => {
  console.error('Provisioning failed:', err);
  process.exit(1);
});
